<?php

namespace ContainerS6n5eUj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G6I1LzyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G6I1Lzy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G6I1Lzy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteEntity' => ['privates', '.errored..service_locator.G6I1Lzy.App\\Entity\\PosteEntity', NULL, 'Cannot autowire service ".service_locator.G6I1Lzy": it needs an instance of "App\\Entity\\PosteEntity" but this type has been excluded in "config/services.yaml".'],
        ], [
            'posteEntity' => 'App\\Entity\\PosteEntity',
        ]);
    }
}
