<?php

namespace ContainerS6n5eUj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteEntity2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G6I1Lzy.App\Entity\PosteEntity' shared service.
     *
     * @return \App\Entity\PosteEntity
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G6I1Lzy": it needs an instance of "App\\Entity\\PosteEntity" but this type has been excluded in "config/services.yaml".');
    }
}
