<?php

namespace ContainerOooDEMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RSs6sP1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RSs6sP1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RSs6sP1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companyCrter' => ['privates', '.errored..service_locator.RSs6sP1.App\\Entity\\CompanyCrters', NULL, 'Cannot autowire service ".service_locator.RSs6sP1": it needs an instance of "App\\Entity\\CompanyCrters" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'companyCrter' => 'App\\Entity\\CompanyCrters',
            'entityManager' => '?',
        ]);
    }
}
