<?php

namespace ContainerOooDEMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyCrtersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RSs6sP1.App\Entity\CompanyCrters' shared service.
     *
     * @return \App\Entity\CompanyCrters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RSs6sP1": it needs an instance of "App\\Entity\\CompanyCrters" but this type has been excluded in "config/services.yaml".');
    }
}
