<?php

namespace ContainerQjOlA8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ThXBizQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.thXBizQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.thXBizQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
        ], [
            'postesRepository' => 'App\\Repository\\PostesRepository',
        ]);
    }
}
