<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'favoris' => [parent::class, 'favoris', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'messagesReceived' => [parent::class, 'messagesReceived', null],
        "\0".parent::class."\0".'messagesSent' => [parent::class, 'messagesSent', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'postes' => [parent::class, 'postes', null],
        "\0".parent::class."\0".'profilsDev' => [parent::class, 'profilsDev', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'email' => [parent::class, 'email', null],
        'favoris' => [parent::class, 'favoris', null],
        'id' => [parent::class, 'id', null],
        'messagesReceived' => [parent::class, 'messagesReceived', null],
        'messagesSent' => [parent::class, 'messagesSent', null],
        'password' => [parent::class, 'password', null],
        'postes' => [parent::class, 'postes', null],
        'profilsDev' => [parent::class, 'profilsDev', null],
        'role' => [parent::class, 'role', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
