<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \App\Entity\Company implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'companyCrters' => [parent::class, 'companyCrters', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'presentation' => [parent::class, 'presentation', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'companyCrters' => [parent::class, 'companyCrters', null],
        'id' => [parent::class, 'id', null],
        'location' => [parent::class, 'location', null],
        'logo' => [parent::class, 'logo', null],
        'nom' => [parent::class, 'nom', null],
        'presentation' => [parent::class, 'presentation', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
