<?php

namespace ContainerTOZQzWj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilsDevService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B1hyQMq.App\Entity\ProfilsDev' shared service.
     *
     * @return \App\Entity\ProfilsDev
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.B1hyQMq": it needs an instance of "App\\Entity\\ProfilsDev" but this type has been excluded in "config/services.yaml".');
    }
}
