<?php

namespace ContainerMMuxJN4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLangages2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PUqINFa.App\Entity\Langages' shared service.
     *
     * @return \App\Entity\Langages
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PUqINFa": it needs an instance of "App\\Entity\\Langages" but this type has been excluded in "config/services.yaml".');
    }
}
