<?php

namespace ContainerZy8GAnL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyCrters2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZndRrER.App\Entity\CompanyCrters' shared service.
     *
     * @return \App\Entity\CompanyCrters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZndRrER": it needs an instance of "App\\Entity\\CompanyCrters" but this type has been excluded in "config/services.yaml".');
    }
}
