<?php

namespace ContainerZy8GAnL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hI9ENSs.App\Entity\Postes' shared service.
     *
     * @return \App\Entity\Postes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hI9ENSs": it needs an instance of "App\\Entity\\Postes" but this type has been excluded in "config/services.yaml".');
    }
}
