<?php

namespace ContainerMJPIfov;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B1hyQMqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B1hyQMq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B1hyQMq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profilsDev' => ['privates', '.errored..service_locator.B1hyQMq.App\\Entity\\ProfilsDev', NULL, 'Cannot autowire service ".service_locator.B1hyQMq": it needs an instance of "App\\Entity\\ProfilsDev" but this type has been excluded in "config/services.yaml".'],
        ], [
            'profilsDev' => 'App\\Entity\\ProfilsDev',
        ]);
    }
}
