<?php

namespace ContainerENgERy9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F9cqnJVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F9cqnJV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F9cqnJV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'posteEntity' => ['privates', '.errored.ZRHY7my', NULL, 'Cannot determine controller argument for "App\\Controller\\PosteController::edit()": the $posteEntity argument is type-hinted with the non-existent class or interface: "App\\Entity\\PosteEntity".'],
        ], [
            'entityManager' => '?',
            'posteEntity' => '?',
        ]);
    }
}
