<?php

namespace ContainerENgERy9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IUNwvJOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iUNwvJO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iUNwvJO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteEntity' => ['privates', '.errored.VRoXo9T', NULL, 'Cannot determine controller argument for "App\\Controller\\PosteController::show()": the $posteEntity argument is type-hinted with the non-existent class or interface: "App\\Entity\\PosteEntity".'],
        ], [
            'posteEntity' => '?',
        ]);
    }
}
