<?php

namespace ContainerENgERy9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KXpHCiHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kXpHCiH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kXpHCiH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteEntityRepository' => ['privates', '.errored.5KxZIba', NULL, 'Cannot determine controller argument for "App\\Controller\\PosteController::index()": the $posteEntityRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PosteEntityRepository".'],
        ], [
            'posteEntityRepository' => '?',
        ]);
    }
}
