<?php

namespace ContainerENgERy9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5KxZIbaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5KxZIba' shared service.
     *
     * @return \App\Repository\PosteEntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\PosteController::index()": the $posteEntityRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PosteEntityRepository".');
    }
}
