<?php

namespace ContainerOiYJkaZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OkAj05lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OkAj05l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OkAj05l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profilsDevRepository' => ['privates', 'App\\Repository\\ProfilsDevRepository', 'getProfilsDevRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'profilsDevRepository' => 'App\\Repository\\ProfilsDevRepository',
            'security' => '?',
        ]);
    }
}
