<?php

namespace ContainerOiYJkaZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Un8E4VgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Un8E4Vg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Un8E4Vg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepositoryService', true],
            'langagesRepository' => ['privates', 'App\\Repository\\LangagesRepository', 'getLangagesRepositoryService', true],
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
        ], [
            'companyRepository' => 'App\\Repository\\CompanyRepository',
            'langagesRepository' => 'App\\Repository\\LangagesRepository',
            'postesRepository' => 'App\\Repository\\PostesRepository',
        ]);
    }
}
