<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xuc8T0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xuc8T0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xuc8T0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xuc8T0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xuc8T0\App_KernelDevDebugContainer([
    'container.build_hash' => '0xuc8T0',
    'container.build_id' => '7db464b2',
    'container.build_time' => 1735913390,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xuc8T0');
