<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMWPwRiD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMWPwRiD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMWPwRiD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMWPwRiD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMWPwRiD\App_KernelDevDebugContainer([
    'container.build_hash' => 'MWPwRiD',
    'container.build_id' => 'a870142a',
    'container.build_time' => 1736206517,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMWPwRiD');
