<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'app_company_index' => [[], ['_controller' => 'App\\Controller\\CompanyController::index'], [], [['text', '/company']], [], [], []],
    'app_company_new' => [[], ['_controller' => 'App\\Controller\\CompanyController::new'], [], [['text', '/company/new']], [], [], []],
    'app_company_show' => [['id'], ['_controller' => 'App\\Controller\\CompanyController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], [], []],
    'app_company_edit' => [['id'], ['_controller' => 'App\\Controller\\CompanyController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], [], []],
    'app_company_delete' => [['id'], ['_controller' => 'App\\Controller\\CompanyController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], [], []],
    'app_landing' => [[], ['_controller' => 'App\\Controller\\LandingController::index'], [], [['text', '/']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'App\Controller\AuthController::login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\AuthController::logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\CompanyController::index' => [[], ['_controller' => 'App\\Controller\\CompanyController::index'], [], [['text', '/company']], [], [], []],
    'App\Controller\CompanyController::new' => [[], ['_controller' => 'App\\Controller\\CompanyController::new'], [], [['text', '/company/new']], [], [], []],
    'App\Controller\CompanyController::show' => [['id'], ['_controller' => 'App\\Controller\\CompanyController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], [], []],
    'App\Controller\CompanyController::edit' => [['id'], ['_controller' => 'App\\Controller\\CompanyController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], [], []],
    'App\Controller\CompanyController::delete' => [['id'], ['_controller' => 'App\\Controller\\CompanyController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], [], []],
    'App\Controller\LandingController::index' => [[], ['_controller' => 'App\\Controller\\LandingController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\RegistrationController::verifyUserEmail' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
];
