<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_landing' => [[], ['_controller' => 'App\\Controller\\LandingController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LandingController::login'], [], [['text', '/login']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\LandingController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\LandingController::index' => [[], ['_controller' => 'App\\Controller\\LandingController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LandingController::login' => [[], ['_controller' => 'App\\Controller\\LandingController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\LandingController::register' => [[], ['_controller' => 'App\\Controller\\LandingController::register'], [], [['text', '/register']], [], [], []],
];
