<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'app_landing' => [[], ['_controller' => 'App\\Controller\\LandingController::index'], [], [['text', '/']], [], [], []],
    'app_profil' => [[], ['_controller' => 'App\\Controller\\LandingController::profi'], [], [['text', '/profil']], [], [], []],
    'app_editprofil' => [[], ['_controller' => 'App\\Controller\\LandingController::editprofil'], [], [['text', '/editprofil']], [], [], []],
    'target_path' => [[], ['_controller' => 'App\\Controller\\LandingController::homeLogin'], [], [['text', '/dev']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'App\Controller\AuthController::login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\AuthController::logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\LandingController::index' => [[], ['_controller' => 'App\\Controller\\LandingController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LandingController::profi' => [[], ['_controller' => 'App\\Controller\\LandingController::profi'], [], [['text', '/profil']], [], [], []],
    'App\Controller\LandingController::editprofil' => [[], ['_controller' => 'App\\Controller\\LandingController::editprofil'], [], [['text', '/editprofil']], [], [], []],
    'App\Controller\LandingController::homeLogin' => [[], ['_controller' => 'App\\Controller\\LandingController::homeLogin'], [], [['text', '/dev']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\RegistrationController::verifyUserEmail' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
];
